kind: ConfigMap
apiVersion: v1
metadata:
  name: appconfig
data:
  API_KEY: hJ7kTScEr4dT5sWofAwOXapXGAt34KcA
  destinations: |
    [{"name": "apihub_sandbox","url": "https://sandbox.api.sap.com"}]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s4mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s4mock
  template:
    metadata:
      labels:
        app: s4mock
        version: v1
    spec:
      containers:
      # replace the repository URL with your own repository (e.g. {DockerID}/http-db-service:0.0.x for Docker Hub).
      - image: docker.pkg.github.com/sammok83/teched2020-developer-keynote/s4mock:latest

        imagePullPolicy: Always
        name: s4mock
        ports:
        - name: http
          containerPort: 5000
        resources:
          limits:
            memory: 1000Mi
          requests:
            memory: 32Mi
        envFrom:
          - configMapRef:
              name: appconfig
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: s4mock
  labels:
    app: s4mock
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  selector:
    app: s4mock


---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: s4mock
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: s4mock
    port: 5000
    host: s4mock
  rules:
    - path: /.*
      methods: ["GET","POST","PUT","DELETE","PATCH","HEAD"]
      accessStrategies:
        - handler: noop
          config: {}
